installer.sh: workaround for sandbox builds
The new default nix.useSandbox = true breaks calling nix-env from
nixos-enter with the error

error: cloning builder process: Operation not permitted

Until a proper fix is found, we explicitely disable sandbox builds
in the installer script when generating the final configuration
on the install target.